package net.jeremycheng.Calculator;

import java.util.Scanner;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App
{
	private static final String EXIT_TOKEN = "exit";
	private final Calculator calculator;

	public App()
	{
		calculator = new Calculator();
	}

	public void go()
	{
		try (Scanner scanner = new Scanner(System.in))
		{
			while (true)
			{
				System.out.print("Enter an expression to evaluate: ");
				String input = scanner.nextLine();
				if (input.toLowerCase().equals(EXIT_TOKEN))
				{
					break;
				}
				try
				{
					System.out.println("Result: " + calculator.evaluate(input));
				} catch (InvalidInputException e)
				{
					System.out.println("ERROR: " + e.getMessage());
				}
			}

		}
		System.out.println("Thanks for playing...");

	}

	public static void main(String[] args)
	{
		App app = new App();
		app.go();
	}
}
