package net.jeremycheng.Calculator;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
    	Calculator cip = new Calculator();
    	System.out.println(cip.evaluateExpression("1"));
    	System.out.println(cip.evaluateExpression("add(1,1)"));
    	System.out.println(cip.evaluateExpression("mul(2,2)"));
    	System.out.println(cip.evaluateExpression("add(4,add(2,2))"));
    }
}
